apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: mysql
  DB_USER: root
  DB_PASSWORD: passwd
---
# but we should encode the secret values
# by using echo -n 'mysql' | base64
# bXlzcWw=
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: bXlzcWw=
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzc3dk
# to decode

# echo -n 'bXlzcWw=' | base64 --decode


