apiVersion: v1
kind: Service
# its a good practice to add service first
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
      # - protocol: 'TCP'
      #   port: 443
      #   targetPort: 443
  type: LoadBalancer
# you must seperate by 3 dashes it means new object in yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template:
    # kind is redundant and not required since its always a pod
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: mrfinesse47/kub-first-app:rex
