apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogopher
spec:
  selector:
    matchLabels:
      app: hellogopher
  replicas: 1
  template:
    metadata:
      labels:
        app: hellogopher
    spec:
      containers:
        - name: hellogopher
          image: mrfinesse47/hellogopher:2.0

          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
